<a href="https://colab.research.google.com/github/Cliffochi/aviva_data_science_course/blob/main/implementing_matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Calculating matrix multiplication by hand

Matrix Multiplication of A and B

Given Matrices:

Matrix A:

[[-1, 2, 3],

 [4, -5, 6],

 [7, 8, -9]]

Matrix B:

[[0, 2, 1],

 [0, 2, -8],

 [2, 9, -1]]

Step-by-Step Calculation:

Row 1 of A × Columns of B:

C11 = (-1)(0) + (2)(0) + (3)(2) = 6

C12 = (-1)(2) + (2)(2) + (3)(9) = 29

C13 = (-1)(1) + (2)(-8) + (3)(-1) = -20

Row 2 of A × Columns of B:

C21 = (4)(0) + (-5)(0) + (6)(2) = 12

C22 = (4)(2) + (-5)(2) + (6)(9) = 52

C23 = (4)(1) + (-5)(-8) + (6)(-1) = 38

Row 3 of A × Columns of B:

C31 = (7)(0) + (8)(0) + (-9)(2) = -18

C32 = (7)(2) + (8)(2) + (-9)(9) = -51

C33 = (7)(1) + (8)(-8) + (-9)(-1) = -48

Final Result of AB:

[[6, 29, -20],

 [12, 52, 38],

 [-18, -51, -48]]

In [15]:
# [Question 2] Calculation using NumPy functions
import numpy as np
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# using np.matmul
C0 = np.matmul(A, B)
print("Using np.matmul: \n", C0)

# using np.dot()
C1 = np.dot(A, B)
print("\nUsing @ np.dot: \n", C1, )

# using @ operator
C2 = A @ B
print("\nUsing @ operator: \n", C2)


Using np.matmul: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Using @ np.dot: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Using @ operator: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [17]:
# [Problem 3] Implementing calculations for a certain element
import numpy as np

# Define matrices
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Initialize result matrix
C_manual = np.zeros((3,3), dtype=int)

# Calculate the matrix multiplication manually
for i in range(3): # for every row in A
  for j in range(3): # for every row in B
  # dot product manually computed
    C_manual[i, j] = sum(A[i, k] * B[k, j] for k in range(3))

print("Manually calculated matrix: \n", C_manual)

Manually calculated matrix: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [21]:
# [Problem 4] Creating a function to perform matrix multiplication
import numpy as np

def matrix_multiplier(A, B):
  """
  Computes matrix product of 2 matrices
  takes 2 arguments : A and B matrices
  returns the product of the matrices
  """
  # get dimensions of the matrices
  n, m = A.shape
  x, y = B.shape
  # check if matrices can be multiplied
  if m != x:
    raise ValueError("incompatible")

  # intialise result matrix
  C = np.zeros((n, y), dtype=A.dtype)

  # computing for each element C[i, j]
  for i in range(n):
    for j in range(y):
      # sum
      C[i, j] = sum(A[i, k] * B[k, j] for k in range(m))

  return C

# Compute product
C = matrix_multiplier(A, B)
print("\n Matrix Multiplier", C)


 Matrix Multiplier [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [22]:
import numpy as np

def matrix_multiply(A, B, use_transpose=False):
    """
    Computes matrix product of A and B with input validation.
    Optionally uses transpose for computation.

    Args:
        A (np.ndarray): First matrix (n x m)
        B (np.ndarray): Second matrix (m x p)
        use_transpose (bool): If True, uses transpose method

    Returns:
        np.ndarray: Resulting matrix (n x p)
    """
    # Input validation
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        raise ValueError("Both inputs must be NumPy arrays")

    if A.ndim != 2 or B.ndim != 2:
        raise ValueError("Inputs must be 2D matrices")

    n, m = A.shape
    m2, p = B.shape

    if m != m2:
        raise ValueError(f"Incompatible dimensions: A columns ({m}) != B rows ({m2})")

    # Calculation method selection
    if use_transpose:
        # Method using transpose (Problem 6)
        B_T = B.T
        C = np.zeros((n, p), dtype=A.dtype)
        for i in range(n):
            for j in range(p):
                C[i,j] = sum(A[i,k] * B_T[j,k] for k in range(m))
    else:
        # Standard method (Problem 4)
        C = np.zeros((n, p), dtype=A.dtype)
        for i in range(n):
            for j in range(p):
                C[i,j] = sum(A[i,k] * B[k,j] for k in range(m))

    return C

# Test cases
D = np.array([[1, 2], [3, 4]])  # 2x2
E = np.array([[1, 2, 3]])        # 1x3 (incompatible)

try:
    print(matrix_multiply(D, E))
except ValueError as e:
    print(f"Error: {e}")

# Working example with transpose (Problem 6)
A = np.array([[1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print("\nStandard multiplication:")
print(matrix_multiply(A, B))

print("\nTranspose multiplication:")
print(matrix_multiply(A, B, use_transpose=True))

Error: Incompatible dimensions: A columns (2) != B rows (1)

Standard multiplication:
[[  6  33 -18]
 [ 12  52  38]
 [-18 -51 -48]]

Transpose multiplication:
[[  6  33 -18]
 [ 12  52  38]
 [-18 -51 -48]]
